services:
  - type: web
    name: dinastia-baileys
    runtime: node
    rootDir: .
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: PORT
        value: 3001
      - key: BAILEYS_SECRET
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
